from datetime import date
from typing import Optional
from pydantic import BaseModel

class PersonStatus(BaseModel):

#        One person's activity sumary for the brief, grounded in specific item IDs so every claim is traceable

    
    person: str
    committed: list[str] = []   # item IDs actively being worked
    delivered: list[str] = []   # item IDs moved to Done 
    pending: list[str] = []     # item IDs open, not yet started
    blocked: list[str] = []     # item IDs currently blocked
    had_activity: bool = True   # false if genuinely nothing to report
    

class BlockerFact(BaseModel):
    """A single blocker, ranked-ready, with its source reference."""
    item_id: str
    title: str
    assignee: Optional[str]
    days_blocked: int
    in_risk_log: bool
    
class BriefFacts(BaseModel):
    """The full set of deterministic facts one morning brief.
        Every field here traces back to real snapshot/risk-log data where
        nothing in this model is generated by the model 
    """
    
    sprint_name: str
    sprint_day: int
    sprint_total_days: int
    people: list[PersonStatus]
    blockers: list[BlockerFact]