from typing import Optional
from pydantic import BaseModel


class PersonStatus(BaseModel):
    """One person's activity summary for the brief, grounded in
    specific item IDs so every claim is traceable."""
    person: str
    committed: list[str] = []
    delivered: list[str] = []
    pending: list[str] = []
    blocked: list[str] = []
    had_activity: bool = True


class BlockerFact(BaseModel):
    """A single blocker, ranked-ready, with its source reference."""
    item_id: str
    title: str
    assignee: Optional[str]
    days_blocked: int
    in_risk_log: bool


class BriefFacts(BaseModel):
    """The full set of deterministic facts for one morning brief.
    Every field here traces back to real snapshot/risk-log data —
    nothing in this model is generated by the model."""
    sprint_name: str
    sprint_day: int
    sprint_total_days: int
    people: list[PersonStatus]
    blockers: list[BlockerFact]
    item_titles: dict[str, str] = {}
